# This file contains values from Cookiecutter

default_context:
  project_name: "torchtils"
  project_description: "eds torch utils"
  organization: "ezhang"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "ezhang7423"
  email: "hello@ezhang.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
